/**
 * utils/pdfBuilder.js — Generate ATS-friendly resume PDFs
 * 
 * Produces clean, single-column, serif-font PDFs that pass
 * Applicant Tracking Systems. No tables, no columns, no graphics.
 */

import PDFDocument from 'pdfkit';

/**
 * Generates an ATS-friendly PDF buffer from structured resume text.
 * 
 * @param {string} resumeText - The AI-tailored resume content (Markdown-ish)
 * @returns {Promise<Buffer>} PDF file as a Buffer
 */
export function generateResumePDF(resumeText) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 55, right: 55 },
        info: {
          Title: 'ATS-Tailored Resume — Wingman AI',
          Author: 'Wingman Career Intelligence',
        }
      });

      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const lines = resumeText.split('\n');

      for (const line of lines) {
        let trimmed = line.trim();
        if (!trimmed) {
          doc.moveDown(0.4);
          continue;
        }

        // Section headers (lines starting with ## or all-caps lines)
        if (trimmed.startsWith('## ') || trimmed.startsWith('### ')) {
          const heading = trimmed.replace(/^#{2,3}\s*/, '').replace(/\*\*/g, '').trim();
          doc.moveDown(0.6);
          doc.fontSize(12).font('Helvetica-Bold').text(heading.toUpperCase());
          doc.moveTo(doc.x, doc.y).lineTo(doc.x + 480, doc.y).lineWidth(0.5).stroke('#333333');
          doc.moveDown(0.3);
          continue;
        }

        // Main title (# line — candidate name)
        if (trimmed.startsWith('# ')) {
          const name = trimmed.replace(/^#\s*/, '').replace(/\*\*/g, '').trim();
          doc.fontSize(18).font('Helvetica-Bold').text(name, { align: 'center' });
          doc.moveDown(0.3);
          continue;
        }

        // Bullet points
        if (trimmed.startsWith('- ') || trimmed.startsWith('• ') || trimmed.startsWith('* ')) {
          const bulletContent = trimmed.replace(/^[-•*]\s*/, '');
          const clean = cleanMarkdown(bulletContent);
          doc.fontSize(10).font('Helvetica').text(`•  ${clean}`, { 
            indent: 10,
            lineGap: 2,
            paragraphGap: 2
          });
          continue;
        }

        // Handle bold lines that aren't headers (e.g. "Software Engineer | Company")
        if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
          const boldText = trimmed.replace(/\*\*/g, '').trim();
          doc.fontSize(10.5).font('Helvetica-Bold').text(boldText);
          continue;
        }

        // Regular text
        const cleanText = cleanMarkdown(trimmed);
        doc.fontSize(10).font('Helvetica').text(cleanText, {
          lineGap: 2,
          paragraphGap: 2
        });
      }

      // Footer
      doc.moveDown(2);
      doc.fontSize(7).font('Helvetica-Oblique').fillColor('#999999')
        .text('Generated by Wingman AI — ATS Optimized Resume', { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Strips basic markdown characters and cleans up text for PDF rendering.
 */
function cleanMarkdown(text) {
  return text
    .replace(/\*\*/g, '')      // Remove bold
    .replace(/\*/g, '')       // Remove italics
    .replace(/__/g, '')       // Remove underline
    .replace(/\[(.*?)\]\(.*?\)/g, '$1') // Simplify links: [text](url) -> text
    .replace(/`/g, '')        // Remove code ticks
    .trim();
}
